name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install WiX Toolset
        run: |
          choco install wixtoolset --no-progress -y

      - name: Build with Gradle
        run: .\gradlew clean build jpackage

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: AFK.exe
          path: build/jpackage/*.exe