name: Build and optionally Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: '¿Crear release de GitHub?'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  create-tag:
    if: ${{ github.event.inputs.release == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      tagname: ${{ steps.get_version.outputs.tagname }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from gradle.properties
        id: get_version
        run: |
          VERSION=$(./gradlew -q printVersion)
          echo "tagname=v${VERSION}" >> $GITHUB_OUTPUT

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.get_version.outputs.tagname }}

  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get version
        id: get_version
        run: |
          VERSION=$(./gradlew -q printVersion)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        run: ./gradlew createExe

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: ./build/out/*.exe

  publish-release:
    if: ${{ github.event.inputs.release == 'true' }}
    runs-on: ubuntu-latest
    needs: [create-tag, build]
    steps:
      - name: Download EXE
        uses: actions/download-artifact@v4
        with:
          name: exe
          path: out

      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create-tag.outputs.tagname }}
          name: ${{ needs.create-tag.outputs.tagname }}
          draft: false
          prerelease: false
          files: out/*
