name: Build and Release
on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    outputs:
      tagname: ${{ steps.get_version.outputs.tagname }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from gradle.properties
        id: get_version
        run: |
          VERSION=$(./gradlew -q printVersion)
          echo "tagname=v${VERSION}" >> $GITHUB_OUTPUT

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.get_version.outputs.tagname }}

  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install WiX Toolset
        run: |
          choco install wixtoolset --no-progress -y

      - name: Build with Gradle
        run: .\gradlew clean build jpackage

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: build/jpackage/*.exe

  publish-release:
    runs-on: ubuntu-latest
    needs: [create-tag, build]
    outputs:
      id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Download EXE
        uses: actions/download-artifact@v4
        with:
          name: exe
          path: out

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create-tag.outputs.tagname }}
          name: ${{ needs.create-tag.outputs.tagname }}
          draft: false
          prerelease: false
          files: out/*